export const PARTNER_LIST_REQUEST = "PARTNER_LIST_REQUEST";
export const PARTNER_LIST_SUCCESS = "PARTNER_LIST_SUCCESS";
export const PARTNER_LIST_FAIL = "PARTNER_LIST_FAIL";

export const PARTNER_DETAILS_REQUEST = "PARTNER_DETAILS_REQUEST";
export const PARTNER_DETAILS_SUCCESS = "PARTNER_DETAILS_SUCCESS";
export const PARTNER_DETAILS_FAIL = "PARTNER_DETAILS_FAIL";
